"""Test that formula paragraphs get separate chunks with formula_template_id reference."""

from yuxi.services.domain_factory_service import DomainFactoryService
from yuxi.utils import hashstr


def _service():
    return DomainFactoryService.__new__(DomainFactoryService)


def _make_para(para_id: str, classify_type: str, content: str, **kwargs) -> dict:
    p = {
        "id": para_id,
        "content": content,
        "classify_type": classify_type,
        "title": "",
        "section_path": ["3", "3.3"],
        "section_id": f"sec_{para_id}",
        "template": {},
        **kwargs,
    }
    return p


def test_formula_paragraph_creates_separate_chunk():
    """Formula paragraphs should get their own chunks with formula_template_id."""
    svc = _service()
    task = {
        "source_paragraphs": [
            _make_para(
                "p1",
                "formula",
                "P=Ci/Co\n式中：P－单因子污染指数；",
                template={
                    "formula": {
                        "original": "P=Ci/Co",
                        "format": "text",
                        "purpose": "预测污染物浓度分布",
                        "variables": [
                            {"symbol": "P", "name": "单因子污染指数", "unit": None},
                            {"symbol": "Ci", "name": "污染物浓度", "unit": "mg/m3", "entity_ref": "pollutant_conc"},
                            {"symbol": "Co", "name": "标准浓度限值", "unit": "mg/m3"},
                        ],
                    }
                },
            ),
            _make_para("p2", "narrative", "这是普通叙述段落。"),
        ],
        "structured_blocks": [],
        "domain_label": "coal",
        "document_type": "eia_report",
        "base_info": {},
    }
    doc = svc._build_structured_document(task, "test_file", "test.md")

    # Should have 2 chunks: 1 narrative + 1 formula
    assert len(doc.chunks) == 2, f"Expected 2 chunks, got {len(doc.chunks)}"

    formula_chunks = [c for c in doc.chunks if c["id"].endswith("_formula_1")]
    assert len(formula_chunks) == 1, "Should have 1 formula chunk"

    fc = formula_chunks[0]
    assert fc["formula_template_id"].startswith("FORMULA_"), f"Bad formula_id: {fc['formula_template_id']}"
    assert "P=Ci/Co" in fc["content"]
    assert "单因子污染指数" in fc["content"]
    assert "污染物浓度" in fc["content"]
    assert "mg/m3" in fc["content"]
    assert "pollutant_conc" in fc["content"]


def test_non_formula_paragraphs_no_formula_chunk():
    """Non-formula paragraphs should NOT get formula chunks."""
    svc = _service()
    task = {
        "source_paragraphs": [
            _make_para("p1", "narrative", "普通叙述。"),
            _make_para("p2", "parameter", "参数型段落。"),
        ],
        "structured_blocks": [],
        "domain_label": "",
        "document_type": "",
        "base_info": {},
    }
    doc = svc._build_structured_document(task, "test_file", "test.md")
    formula_chunks = [c for c in doc.chunks if "formula_template_id" in c]
    assert len(formula_chunks) == 0, f"Should have 0 formula chunks, got {len(formula_chunks)}"


def test_formula_chunk_consistent_with_graph_id():
    """formula_template_id should match the ID generated by GraphBuilder."""
    svc = _service()
    original = "P=Ci/Co"
    expected_id = f"FORMULA_{hashstr(original, 12)}"

    task = {
        "source_paragraphs": [
            _make_para(
                "p1",
                "formula",
                original,
                template={"formula": {"original": original, "variables": []}},
            ),
        ],
        "structured_blocks": [],
        "domain_label": "",
        "document_type": "",
        "base_info": {},
    }
    doc = svc._build_structured_document(task, "test_file", "test.md")
    fc = [c for c in doc.chunks if "formula_template_id" in c][0]
    assert fc["formula_template_id"] == expected_id, (
        f"chunk formula_id={fc['formula_template_id']} != expected={expected_id}"
    )
